default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: overgeared
  host: localhost
  port: 5432

development:
  <<: *default
  database: journal_dev
  
test:
  <<: *default
  database: journal_test

production:
  <<: *default
  database: journal_prod